### ISSUE TITLE
Not working on Mac OS X

### ISSUE THREAD

**Issue by matteocorti** [matteocorti/daemonizer#4]
**Original reporter**: _[matteo@corti.li](https://github.com/matteo@corti.li)_

Does not seem to work on Mac OS X:
- log is incomplete
- deamon is not started

**Comment by schnoddelbotz** [comment]
In case you're looking for a quick work-around: OS X comes with `screen` pre-installed...
```bash
screen -L -d -m /path/to/executable
```
Will run the executable, detach it from terminal and log its output -- and you're able to re-attach to the process if needed (using `screen -r`). Generally, I think you'd prefer to use a [LaunchDaemon](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html) on OS X to have your process (re)started automatically at Startup or Login 'as a daemon'. Check [launchd.plist](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html#//apple_ref/doc/man/5/launchd.plist) for options regarding process logging, restart behaviour etc.
Just wanted to state it's probably not a severe problem for OS X [users] at the moment. Still, maybe a short ReadMe outlining differences between alternatives (daemonizer, screen, launchd, nohup?) could be helpful in picking the most adequate solution for a specific usage scenario.
Cheers.

**Comment by matteocorti** [comment]
Fixed thanks to a patch from Jan Hacker
